// frontend/src/components/ui/server-select.tsx
import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import { ChevronDown, X, Search, Check } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Checkbox } from '@/components/ui/checkbox'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Skeleton } from '@/components/ui/skeleton'

// Types
export type Row = Record<string, any>

export interface FetchParams {
  page: number
  limit: number
  search?: string
  sortField?: string
  sortOrder?: 1 | -1
  filters?: Record<string, any>
}

export interface BackendPagination {
  total: number
  page: number
  limit: number
  pageCount: number
  hasNext: boolean
  hasPrev: boolean
}

export interface FetchResult {
  data: Row[]
  pagination: BackendPagination
}

export interface ColumnDef {
  field: string
  header: string
  width?: string
}

export interface ServerSelectProps {
  value?: any | any[]
  onChange?: (value: any | any[]) => void
  onSelected?: (rows: Row | Row[]) => void
  multiple?: boolean
  placeholder?: string
  disabled?: boolean
  pageSize?: number
  overlayWidth?: string | number
  optionLabel?: string | ((row: Row) => string)
  optionValue?: string | ((row: Row) => any)
  dataKeyField?: string
  ensureSelectedVisible?: boolean
  columns: ColumnDef[]
  fetcher: (params: FetchParams) => Promise<FetchResult>
  resolveByValue?: (value: any | any[]) => Promise<Row | Row[] | null>
  showSearch?: boolean
  showClear?: boolean
  dropdownIcon?: React.ReactNode
  className?: string
}

// Debounce hook
function useDebounce<T>(value: T, delay: number): T {
  const [debouncedValue, setDebouncedValue] = useState<T>(value)

  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedValue(value)
    }, delay)

    return () => {
      clearTimeout(handler)
    }
  }, [value, delay])

  return debouncedValue
}

// Mobile detection hook
function useIsMobile() {
  const [isMobile, setIsMobile] = useState(false)

  useEffect(() => {
    const checkIsMobile = () => {
      setIsMobile(window.innerWidth < 640)
    }

    checkIsMobile()
    window.addEventListener('resize', checkIsMobile)
    return () => window.removeEventListener('resize', checkIsMobile)
  }, [])

  return isMobile
}

export const ServerSelect: React.FC<ServerSelectProps> = ({
  value,
  onChange,
  onSelected,
  multiple = false,
  placeholder = 'Chọn...',
  disabled = false,
  pageSize = 20,
  overlayWidth = '720px',
  optionLabel = 'name',
  optionValue = 'id',
  dataKeyField = 'id',
  ensureSelectedVisible = false,
  columns,
  fetcher,
  resolveByValue,
  showSearch = true,
  showClear = true,
  dropdownIcon,
  className,
}) => {
  // State
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [items, setItems] = useState<Row[]>([])
  const [totalRecords, setTotalRecords] = useState(0)
  const [page, setPage] = useState(1)
  const [limit, setLimit] = useState(pageSize)
  const [search, setSearch] = useState('')
  const [sortField, setSortField] = useState<string | undefined>(undefined)
  const [sortOrder, setSortOrder] = useState<1 | -1 | undefined>(undefined)
  const [selectedRows, setSelectedRows] = useState<Row[]>([])

  // Refs
  const abortControllerRef = useRef<AbortController | null>(null)
  const isMobile = useIsMobile()
  const debouncedSearch = useDebounce(search, 600)

  // Computed values
  const resolvedDataKeyField = useMemo(() => {
    if (typeof optionValue === 'string') return optionValue
    return dataKeyField
  }, [optionValue, dataKeyField])

  const selectedList = useMemo(() => {
    if (multiple) return selectedRows
    return selectedRows.length > 0 ? [selectedRows[0]] : []
  }, [selectedRows, multiple])

  const displayText = useMemo(() => {
    if (selectedList.length === 0) return ''
    return selectedList.map(getLabel).join(', ')
  }, [selectedList])

  const showClearButton = useMemo(() => {
    return showClear && !disabled && selectedList.length > 0
  }, [showClear, disabled, selectedList.length])

  // Helper functions
  const getValue = useCallback((row: Row) => {
    if (!row) return row
    if (typeof optionValue === 'function') return optionValue(row)
    if (typeof optionValue === 'string') return row[optionValue]
    return row[resolvedDataKeyField]
  }, [optionValue, resolvedDataKeyField])

  const getLabel = useCallback((row: Row) => {
    if (!row) return ''
    if (typeof optionLabel === 'function') return optionLabel(row)
    if (typeof optionLabel === 'string') return row[optionLabel]
    return row.name ?? row.label ?? row.title ?? `${getValue(row)}`
  }, [optionLabel, getValue])

  // API functions
  const load = useCallback(async () => {
    setLoading(true)
    try {
      if (abortControllerRef.current) {
        abortControllerRef.current.abort()
      }
      abortControllerRef.current = new AbortController()

      const result = await fetcher({
        page,
        limit,
        search: debouncedSearch?.trim() || undefined,
        sortField,
        sortOrder,
      })

      const newItems = Array.isArray(result?.data) ? result.data : []
      const pagination = result?.pagination ?? { total: 0, page: 1, limit: 20 }

      setItems(newItems)
      setTotalRecords(pagination?.total ?? 0)
      if (typeof pagination?.page === 'number') setPage(pagination.page)
      if (typeof pagination?.limit === 'number') setLimit(pagination.limit)

      if (ensureSelectedVisible) {
        pinSelectedToTop(newItems)
      }
    } catch (error) {
      if (error instanceof Error && error.name !== 'AbortError') {
        console.error('Error loading data:', error)
      }
      setItems([])
      setTotalRecords(0)
    } finally {
      setLoading(false)
    }
  }, [page, limit, debouncedSearch, sortField, sortOrder, fetcher, ensureSelectedVisible])

  const pinSelectedToTop = useCallback((newItems: Row[]) => {
    if (!ensureSelectedVisible || selectedList.length === 0) return

    const seen = new Set<any>()
    const pinned = selectedList.filter((row) => {
      const key = getValue(row)
      if (key == null || seen.has(key)) return false
      seen.add(key)
      return true
    })

    const rest = newItems.filter((row) => !seen.has(getValue(row)))
    setItems([...pinned, ...rest])
  }, [ensureSelectedVisible, selectedList, getValue])

  // Sync selection from external value
  const syncFromValue = useCallback(async () => {
    if (value == null || (Array.isArray(value) && value.length === 0)) {
      setSelectedRows([])
      return
    }

    const mapByValue = (rows: Row[], val: any) => rows.find((r) => getValue(r) === val)

    if (multiple && Array.isArray(value)) {
      const found: Row[] = []
      value.forEach((val) => {
        const row = mapByValue(items, val)
        if (row) found.push(row)
      })
      if (found.length === value.length) {
        setSelectedRows(found)
        return
      }
    } else {
      const row = mapByValue(items, value)
      if (row) {
        setSelectedRows([row])
        return
      }
    }

    // Try to resolve by value if not found in current items
    if (resolveByValue) {
      try {
        const resolved = await resolveByValue(value)
        if (Array.isArray(resolved)) {
          setSelectedRows(multiple ? resolved : resolved.slice(0, 1))
        } else if (resolved) {
          setSelectedRows(multiple ? [resolved] : [resolved])
        }
      } catch (error) {
        console.error('Error resolving value:', error)
      }
    }
  }, [value, multiple, items, getValue, resolveByValue])

  // Event handlers
  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearch(e.target.value)
    setPage(1)
  }

  const handleSort = (field: string) => {
    if (sortField === field) {
      setSortOrder(sortOrder === 1 ? -1 : 1)
    } else {
      setSortField(field)
      setSortOrder(1)
    }
    setPage(1)
  }

  const handlePageChange = (newPage: number) => {
    setPage(newPage)
  }

  const handleRowSelect = (row: Row) => {
    if (multiple) {
      const isSelected = selectedRows.some((r) => getValue(r) === getValue(row))
      if (isSelected) {
        setSelectedRows(selectedRows.filter((r) => getValue(r) !== getValue(row)))
      } else {
        setSelectedRows([...selectedRows, row])
      }
    } else {
      setSelectedRows([row])
    }
  }

  const handleRowDoubleClick = (row: Row) => {
    if (!multiple) {
      setSelectedRows([row])
      applySelection([row])
    }
  }

  const applySelection = (rows?: Row[]) => {
    const finalRows = rows || selectedList
    if (multiple) {
      const values = finalRows.map(getValue)
      onChange?.(values)
      onSelected?.(finalRows)
    } else {
      const row = finalRows[0] || null
      const val = row ? getValue(row) : null
      onChange?.(val)
      if (row) onSelected?.(row)
    }
    setOpen(false)
  }

  const clearSelection = () => {
    setSelectedRows([])
    if (multiple) {
      onChange?.([])
      onSelected?.([])
    } else {
      onChange?.(null)
    }
  }

  const isRowSelected = (row: Row) => {
    return selectedRows.some((r) => getValue(r) === getValue(row))
  }

  // Effects
  useEffect(() => {
    load()
  }, [load])

  useEffect(() => {
    syncFromValue()
  }, [syncFromValue])

  useEffect(() => {
    return () => {
      if (abortControllerRef.current) {
        abortControllerRef.current.abort()
      }
    }
  }, [])

  // Render helpers
  const renderPagination = () => {
    const totalPages = Math.ceil(totalRecords / limit)
    const startItem = (page - 1) * limit + 1
    const endItem = Math.min(page * limit, totalRecords)

    if (totalPages <= 1) return null

    return (
      <div className="flex items-center justify-between px-4 py-2 border-t">
        <div className="text-sm text-muted-foreground">
          Hiển thị {startItem}-{endItem} trong {totalRecords} kết quả
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => handlePageChange(page - 1)}
            disabled={page <= 1}
          >
            Trước
          </Button>
          <span className="text-sm">
            Trang {page} / {totalPages}
          </span>
          <Button
            variant="outline"
            size="sm"
            onClick={() => handlePageChange(page + 1)}
            disabled={page >= totalPages}
          >
            Sau
          </Button>
        </div>
      </div>
    )
  }

  const overlayStyle = useMemo(() => ({
    width: isMobile
      ? '96vw'
      : typeof overlayWidth === 'number'
        ? `${overlayWidth}px`
        : overlayWidth,
    maxWidth: '98vw',
    maxHeight: isMobile ? '85vh' : '80vh',
  }), [isMobile, overlayWidth])

  return (
    <div className={cn('w-full', className)}>
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <Button
            variant="outline"
            role="combobox"
            aria-expanded={open}
            className={cn(
              'w-full justify-between',
              !displayText && 'text-muted-foreground',
              disabled && 'opacity-60 pointer-events-none'
            )}
            disabled={disabled}
          >
            <span className="truncate">
              {displayText || placeholder}
            </span>
            <div className="flex items-center gap-1">
              {showClearButton && (
                <X
                  className="h-4 w-4 text-muted-foreground hover:text-destructive cursor-pointer"
                  onClick={(e) => {
                    e.stopPropagation()
                    clearSelection()
                  }}
                />
              )}
              {dropdownIcon || <ChevronDown className="h-4 w-4 shrink-0 opacity-50" />}
            </div>
          </Button>
        </PopoverTrigger>
        <PopoverContent
          className="w-auto p-0"
          style={overlayStyle}
          align="start"
        >
          <div className="flex flex-col">
            {/* Header / Search */}
            {showSearch && (
              <div className="flex items-center gap-2 p-3 border-b">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    placeholder="Tìm kiếm..."
                    value={search}
                    onChange={handleSearchChange}
                    className="pl-9"
                  />
                </div>
              </div>
            )}

            {/* Table */}
            <div className="flex-1">
              <ScrollArea className="h-[380px]">
                <Table>
                  <TableHeader>
                    <TableRow>
                      {multiple && (
                        <TableHead className="w-12">
                          <Checkbox
                            checked={selectedList.length > 0 && selectedList.length === items.length}
                            onCheckedChange={(checked) => {
                              if (checked) {
                                setSelectedRows([...items])
                              } else {
                                setSelectedRows([])
                              }
                            }}
                          />
                        </TableHead>
                      )}
                      {columns.map((col) => (
                        <TableHead
                          key={col.field}
                          className={cn(
                            'cursor-pointer hover:bg-muted/50',
                            col.width && `w-[${col.width}]`
                          )}
                          onClick={() => handleSort(col.field)}
                        >
                          <div className="flex items-center gap-2">
                            {col.header}
                            {sortField === col.field && (
                              <span className="text-xs">
                                {sortOrder === 1 ? '↑' : '↓'}
                              </span>
                            )}
                          </div>
                        </TableHead>
                      ))}
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {loading ? (
                      Array.from({ length: 5 }).map((_, i) => (
                        <TableRow key={i}>
                          {multiple && (
                            <TableCell>
                              <Skeleton className="h-4 w-4" />
                            </TableCell>
                          )}
                          {columns.map((col) => (
                            <TableCell key={col.field}>
                              <Skeleton className="h-4 w-full" />
                            </TableCell>
                          ))}
                        </TableRow>
                      ))
                    ) : items.length === 0 ? (
                      <TableRow>
                        <TableCell
                          colSpan={columns.length + (multiple ? 1 : 0)}
                          className="text-center text-muted-foreground py-8"
                        >
                          Không có dữ liệu
                        </TableCell>
                      </TableRow>
                    ) : (
                      items.map((row, index) => (
                        <TableRow
                          key={getValue(row) || index}
                          className={cn(
                            'cursor-pointer hover:bg-muted/50',
                            isRowSelected(row) && 'bg-muted'
                          )}
                          onClick={() => handleRowSelect(row)}
                          onDoubleClick={() => handleRowDoubleClick(row)}
                        >
                          {multiple && (
                            <TableCell>
                              <Checkbox
                                checked={isRowSelected(row)}
                                onChange={() => handleRowSelect(row)}
                              />
                            </TableCell>
                          )}
                          {columns.map((col) => (
                            <TableCell key={col.field} className="truncate">
                              {row[col.field]}
                            </TableCell>
                          ))}
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </ScrollArea>
            </div>

            {/* Pagination */}
            {renderPagination()}

            {/* Footer */}
            <div className="flex justify-end gap-2 p-3 border-t">
              <Button variant="outline" size="sm" onClick={() => setOpen(false)}>
                Đóng
              </Button>
              <Button
                size="sm"
                disabled={selectedList.length === 0}
                onClick={() => applySelection()}
              >
                <Check className="h-4 w-4 mr-2" />
                Chọn
              </Button>
            </div>
          </div>
        </PopoverContent>
      </Popover>
    </div>
  )
}

// frontend_vue/src/components/ServerSelect.vue
<script setup lang="ts">
import { ref, watch, computed, onMounted, onBeforeUnmount } from 'vue'
import Popover from 'primevue/popover'
import DataTable, { DataTableSortEvent, DataTablePageEvent } from 'primevue/datatable'
import Column from 'primevue/column'
import InputText from 'primevue/inputtext'
import Button from 'primevue/button'
import IconField from 'primevue/iconfield'
import InputIcon from 'primevue/inputicon'

type Row = Record<string, any>

interface FetchParams {
  page: number
  limit: number
  search?: string
  sortField?: string
  sortOrder?: 1 | -1
  filters?: Record<string, any>
}

interface BackendPagination {
  total: number
  page: number
  limit: number
  pageCount: number
  hasNext: boolean
  hasPrev: boolean
}

interface FetchResult {
  data: Row[]
  pagination: BackendPagination
}

interface ColumnDef {
  field: string
  header: string
  width?: string
}

const props = defineProps<{
  modelValue: any | any[]
  multiple?: boolean
  placeholder?: string
  disabled?: boolean
  pageSize?: number
  overlayWidth?: string | number
  optionLabel?: string | ((row: Row) => string)
  optionValue?: string | ((row: Row) => any)
  dataKeyField?: string
  ensureSelectedVisible?: boolean
  columns: ColumnDef[]
  fetcher: (params: FetchParams) => Promise<FetchResult>
  resolveByValue?: (value: any | any[]) => Promise<Row | Row[] | null>
  showSearch?: boolean
  showClear?: boolean
  dropdownIcon?: string
}>()

// Field khóa duy nhất cho DataTable và logic getValue()
const resolvedDataKeyField = computed(() => {
  if (typeof props.optionValue === 'string') return props.optionValue
  return props.dataKeyField || 'id'
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: any | any[]): void
  (e: 'change', value: any | any[]): void
  (e: 'selected', rows: Row | Row[]): void
}>()

// Refs
const op = ref<InstanceType<typeof Popover> | null>(null)
const table = ref<InstanceType<typeof DataTable> | null>(null)

const loading = ref(false)
const items = ref<Row[]>([])
const totalRecords = ref(0)

const page = ref(1)
const limit = ref(props.pageSize ?? 20)
const search = ref('')
const sortField = ref<string | undefined>(undefined)
const sortOrder = ref<1 | -1 | undefined>(undefined)

// Selection state (single = object/null, multiple = array)
const selectedRows = ref<any>(props.multiple ? [] : null)
const selectedList = computed<Row[]>(() =>
  Array.isArray(selectedRows.value)
    ? selectedRows.value
    : (selectedRows.value ? [selectedRows.value] : [])
)

// Value <-> Label helpers
const getValue = (row: Row) => {
  if (!row) return row
  if (typeof props.optionValue === 'function') return (props.optionValue as any)(row)
  if (typeof props.optionValue === 'string') return row[props.optionValue]
  return row[resolvedDataKeyField.value]
}
const getLabel = (row: Row) => {
  if (!row) return ''
  if (typeof props.optionLabel === 'function') return (props.optionLabel as any)(row)
  if (typeof props.optionLabel === 'string') return row[props.optionLabel]
  return row.name ?? row.label ?? row.title ?? `${getValue(row)}`
}
const displayText = computed(() => {
  const rows = selectedList.value
  return rows.length ? rows.map(getLabel).join(', ') : ''
})

const showClearButton = computed(() => {
  return props.showClear && !props.disabled && (
    (props.multiple && selectedList.value.length > 0) ||
    (!props.multiple && selectedList.value.length > 0)
  )
})

// Responsive detection
const isMobile = ref(false)
const updateIsMobile = () => { isMobile.value = window.innerWidth < 640 }
onMounted(() => {
  updateIsMobile()
  window.addEventListener('resize', updateIsMobile)
})
onBeforeUnmount(() => window.removeEventListener('resize', updateIsMobile))

// Overlay & table sizing for responsive
const overlayStyle = computed(() => ({
  width: isMobile.value
    ? '96vw'
    : (typeof props.overlayWidth === 'number'
        ? props.overlayWidth + 'px'
        : (props.overlayWidth || '720px')),
  maxWidth: '98vw',
  maxHeight: isMobile.value ? '85vh' : '80vh'
}))
const dtScrollHeight = computed(() => (isMobile.value ? '55vh' : '380px'))
const tableMinWidth = computed(() => (isMobile.value ? '0' : '560px'))

// API loader
let currentAbort: AbortController | null = null
async function load() {
  loading.value = true
  try {
    if (currentAbort) currentAbort.abort()
    currentAbort = new AbortController()

    const res = await props.fetcher({
      page: page.value,
      limit: limit.value,
      search: search.value?.trim() || undefined,
      sortField: sortField.value,
      sortOrder: sortOrder.value
    })

    items.value = Array.isArray(res?.data) ? res.data : []
    const p = res?.pagination ?? { total: 0, page: 1, limit: 20 }
    totalRecords.value = p?.total ?? 0
    if (typeof p?.page === 'number') page.value = p.page
    if (typeof p?.limit === 'number') limit.value = p.limit

    pinSelectedToTop()
  } catch (err) {
    items.value = []
    totalRecords.value = 0
  } finally {
    loading.value = false
  }
}

// Debounce search
let searchTimer: any
function onSearchInput(val: string) {
  search.value = val
  clearTimeout(searchTimer)
  searchTimer = setTimeout(() => {
    page.value = 1
    load()
  }, 600)
}

function onSort(e: DataTableSortEvent) {
  // @ts-ignore
  sortField.value = (e.sortField as string) || undefined
  // @ts-ignore
  sortOrder.value = (e.sortOrder as 1 | -1) || undefined
  page.value = 1
  load()
}

function onPage(e: DataTablePageEvent) {
  const newPage = Math.floor(e.first / e.rows) + 1
  const newLimit = e.rows
  if (newPage !== page.value || newLimit !== limit.value) {
    page.value = newPage
    limit.value = newLimit
    load()
  }
}

// 🔹 Phương án A: ghim hàng đã chọn lên đầu trang hiện tại
function pinSelectedToTop() {
  if (!props.ensureSelectedVisible) return
  const sel = selectedList.value
  if (!sel.length) return

  const seen = new Set<any>()
  const pinned = sel.filter(r => {
    const k = getValue(r)
    if (k == null || seen.has(k)) return false
    seen.add(k)
    return true
  })

  // loại bỏ những hàng đã pin khỏi danh sách hiện tại, rồi ghép vào đầu
  const rest = items.value.filter(r => !seen.has(getValue(r)))
  items.value = [...pinned, ...rest]
}

function openPanel(evt: MouseEvent) {
  if (props.disabled) return
  op.value?.toggle(evt)
}
function closePanel() { op.value?.hide() }

function applySelection() {
  if (props.multiple) {
    const values = selectedList.value.map(getValue)
    emit('update:modelValue', values)
    emit('change', values)
    emit('selected', [...selectedList.value])
  } else {
    const row = selectedList.value[0] || null
    const value = row ? getValue(row) : null
    emit('update:modelValue', value)
    emit('change', value)
    if (row) emit('selected', row)
  }
  closePanel()
}

function clearSelection() {
  if (props.multiple) {
    selectedRows.value = []
    emit('update:modelValue', [])
    emit('change', [])
    emit('selected', [])
  } else {
    selectedRows.value = null
    emit('update:modelValue', null)
    emit('change', null)
  }
}

function onRowDblClick(e: { data: Row }) {
  if (props.multiple) return
  selectedRows.value = e.data
  applySelection()
}

// Sync selection when modelValue changes externally
async function syncFromValue() {
  const v = props.modelValue
  if (v == null || (Array.isArray(v) && v.length === 0)) {
    selectedRows.value = props.multiple ? [] : null
    return
  }
  const mapByValue = (rows: Row[], value: any) => rows.find((r) => getValue(r) === value)

  if (props.multiple && Array.isArray(v)) {
    const found: Row[] = []
    v.forEach((val) => {
      const r = mapByValue(items.value, val)
      if (r) found.push(r)
    })
    if (found.length === v.length) {
      selectedRows.value = found
      return
    }
  } else {
    const r = mapByValue(items.value, v)
    if (r) {
      selectedRows.value = r
      return
    }
  }

  if (props.resolveByValue) {
    const res = await props.resolveByValue(v)
    if (Array.isArray(res)) selectedRows.value = props.multiple ? res : (res[0] ?? null)
    else if (res) selectedRows.value = props.multiple ? [res] : res
  }
}

watch(() => props.modelValue, syncFromValue)

onMounted(async () => {
  await load()
  await syncFromValue()
  pinSelectedToTop()
})
</script>

<template>
  <div class="server-select w-full">
    <div
      class="ss-input d-flex align-items-center justify-content-between gap-2 form-control cursor-pointer"
      :class="{ 'opacity-60 pointer-events-none': disabled }"
      @click="openPanel($event)"
      tabindex="0"
    >
      <span class="text-truncate small" :class="{ 'text-body-secondary': !displayText }">
        {{ displayText || placeholder || 'Chọn...' }}
      </span>
      <div class="d-flex align-items-center gap-1">
        <i 
          v-if="showClearButton"
          class="pi pi-times clear-icon"
          @click.stop="clearSelection"
          title="Xóa lựa chọn"
        />
        <i :class="dropdownIcon || 'pi pi-chevron-down'" />
      </div>
    </div>

    <Popover
      ref="op"
      appendTo="body"
      :showCloseIcon="isMobile"
      :dismissable="true"
      class="server-select-panel shadow-lg rounded-3 border-0"
      :style="overlayStyle"
    >
      <!-- Header / Search -->
      <div class="ss-header d-flex align-items-center gap-2 px-3 py-2 border-bottom bg-body sticky-top">
        <IconField class="flex-grow-1">
          <InputIcon><i class="pi pi-search" /></InputIcon>
          <InputText
            class="w-100"
            placeholder="Tìm kiếm..."
            @input="onSearchInput(($event.target as HTMLInputElement).value)"
          />
        </IconField>
      </div>

      <!-- Table -->
      <div class="ss-table-wrap">
        <DataTable
          ref="table"
          :value="items"
          lazy
          paginator
          paginatorPosition="bottom"
          :rows="limit"
          :first="(page - 1) * limit"
          :totalRecords="totalRecords"
          :loading="loading"
          :sortField="sortField"
          :sortOrder="sortOrder"
          :selectionMode="multiple ? 'multiple' : 'single'"
          :dataKey="resolvedDataKeyField"
          v-model:selection="selectedRows"
          @sort="onSort"
          @page="onPage"
          @row-dblclick="onRowDblClick"
          scrollable
          :scrollHeight="dtScrollHeight"
          responsiveLayout="scroll"
          :showGridlines="false"
          :tableStyle="{ minWidth: tableMinWidth }"
          class="ss-table"
        >
          <Column v-if="multiple" selectionMode="multiple" headerStyle="width: 3rem"></Column>
          <Column
            v-for="col in columns"
            :key="col.field"
            :field="col.field"
            :header="col.header"
            :style="{ width: col.width }"
            sortable
          >
            <template #body="{ data }">
              <span class="text-truncate d-block">{{ data[col.field] }}</span>
            </template>
          </Column>

          <template #empty>
            <div class="text-center text-body-secondary py-4 small">Không có dữ liệu</div>
          </template>
        </DataTable>
      </div>

      <!-- Footer -->
      <div class="ss-footer d-flex justify-content-end gap-2 px-3 py-2 border-top bg-body sticky-bottom">
        <Button label="Đóng" icon="pi pi-times" severity="secondary" size="small" @click="closePanel" />
        <Button label="Chọn" icon="pi pi-check" size="small" :disabled="!selectedList.length" @click="applySelection" />
      </div>
    </Popover>
  </div>
</template>

<style scoped>
.server-select .ss-input { min-height: 38px; }

/* Cho panel co giãn, nội dung linh hoạt */
.server-select-panel { overflow: hidden; }
.ss-table-wrap { max-height: 100%; }

/* Giữ 1 dòng, có thể cuộn ngang khi hẹp */
.server-select .ss-table :deep(.p-datatable-tbody > tr > td) { white-space: nowrap; }

/* Clear button styling */
.clear-icon {
  font-size: 0.875rem;
  color: #6b7280;
  cursor: pointer;
  padding: 0.25rem;
  border-radius: 50%;
  transition: all 0.2s ease;
}

.clear-icon:hover {
  color: #ef4444;
  background-color: #fef2f2;
}

.clear-icon:active {
  transform: scale(0.95);
}

/* Mobile tweaks */
@media (max-width: 640px) {
  .ss-header { padding: .5rem .75rem; }
  .ss-footer { padding: .5rem .75rem; }
}
</style>
